version: '2'

services:
  db:
    image: mariadb:10.4.11-bionic
    volumes:
        - mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: "baklAD&^$ui123S"
        MYSQL_DATABASE: "website"
        MYSQL_USER: "website"
        MYSQL_PASSWORD: "t3sting^3"
    ports:
     - 3306:3307
  web:
    build: web/
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./src/:/var/www/
volumes:
  mysql: